% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/ParamRead.R
\name{ParamRead}
\alias{ParamRead}
\title{Read parameter file for PRMS}
\usage{
ParamRead(prms.param.path, verbose = FALSE)
}
\arguments{
\item{prms.param.path}{File Path and File Name for Parameter File}

\item{verbose}{Verbose flag}
}
\value{
Object with Parameter Value
}
\description{
Functionalization o the script
}
